MACRO(OPENMS_CONTRIB_BUILD_ARROW)
    OPENMS_LOGHEADER_LIBRARY("ARROW") 
    if(MSVC)
      set(ZIP_ARGS "x -y -osrc")
    else()
      set(ZIP_ARGS "xzf")
    endif()
    OPENMS_SMARTEXTRACT(ZIP_ARGS ARCHIVE_ARROW "ARROW" "gdb_arrow.py")
    if(UNIX AND NOT APPLE)
      set(LINUX TRUE) #make a linux flag for readability.
    endif()    
    set( ARROW_BUILD_TYPE "static")
    if (BUILD_SHARED_LIBRARIES)
	  set( ARROW_BUILD_TYPE "shared")
    endif()
  

    ## Our list of cmake args -> taken from a an arrow cpp build preset
    set(_ARROW_CMAKE_ARGS
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBRARIES}
    -DCMAKE_INSTALL_PREFIX=${PROJECT_BINARY_DIR}
    -DCMAKE_BUILD_TYPE=Release
    -DARROW_ACERO=ON \

    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DARROW_BUILD_STATIC=ON \
    -DARROW_COMPUTE=ON \
    -DARROW_CSV=ON \
    -DARROW_DATASET=ON \
    -DARROW_FILESYSTEM=ON \
    -DARROW_JSON=ON \
    -DARROW_FLIGHT=ON \
    -DARROW_GANDIVA=ON \
    -DARROW_JSON=ON \
    -DARROW_PARQUET=ON \
    -DARROW_WITH_BROTLI=ON \
    -DARROW_WITH_BZ2=ON \
    -DARROW_WITH_LZ4=ON \
    -DARROW_WITH_SNAPPY=ON \
    -DARROW_WITH_ZLIB=ON \
    -DARROW_WITH_ZSTD=ON \
    -DARROW_POSITION_INDEPENDENT_CODE=ON)
    

    
ENDMACRO(OPENMS_CONTRIB_BUILD_ARROW)