on:
  workflow_dispatch:
  push:
    branches:        
      - master
      - 'release/**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Checkout Dockerfiles
        shell: bash # uses git bash on windows
        run: |
            git clone https://github.com/OpenMS/dockerfiles
            cd dockerfiles
            # for release try to checkout a corresponding release branch first
            git checkout ${{ steps.extract_branch.outputs.branch }} || git checkout master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          file: dockerfiles/contrib/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref }}
            ghcr.io/${{ github.repository }}:latest
